### PR TITLE
#7 Add polite handing of unknown schema

### LINKED ISSUE #7: Add polite handing of unknown schema
Right now it looks like that:

```
2.6.6 :002 > Iuliia::Schema['mvd']
Traceback (most recent call last):
        7: from bin/console:15:in `<main>'
        6: from (irb):2
        5: from (irb):2:in `rescue in irb_binding'
        4: from /Users/user/RubymineProjects/iuliia-rb/lib/iuliia/schema.rb:11:in `[]'
        3: from /Users/user/RubymineProjects/iuliia-rb/lib/iuliia/schema.rb:25:in `block in schemas'
        2: from /Users/user/RubymineProjects/iuliia-rb/lib/iuliia/schema.rb:29:in `load_schema'
        1: from /Users/user/RubymineProjects/iuliia-rb/lib/iuliia/schema.rb:29:in `read'
Errno::ENOENT (No such file or directory @ rb_sysopen - lib/schemas/mvd.json)
```

Better if we will return more polite and understandable error.

### PR DESCRIPTION
**Pull request by theendcomplete**
- Safe `File.open`
- `nil` is returned when no schema is available
- specs

example:

```
irb(main):001:0> Iuliia::Schema['gost_779a']
Failed to load schema. No such file or directory @ rb_sysopen - lib/schemas/gost_779a.json
=> nil
irb(main):002:0> 
```

### CODE REVIEW

File: lib/iuliia/schema.rb [hunk 1]
```diff
@@ -28,6 +27,8 @@ def schemas
 
       def load_schema(name)
         JSON.parse(File.read("lib/schemas/#{name}.json"), object_class: OpenStruct, symbolize_names: true)
+      rescue Errno::ENOENT => e
+        puts "Failed to load schema. #{e.message}"
```
Comment (adnikiforov) [inline lib/iuliia/schema.rb]: Honestly, I think it will be better to throw `Exception`, maybe even custom class exception. Thing is, wrong schema name is quite critical event. No schema - no work, full stop.

But original exception is not fully understandable for a random gem user. So we need to give him clear message: check your schema name, you did it wrong.

File: spec/iuliia/schema_spec.rb [hunk 2]
```diff
@@ -0,0 +1,27 @@
+# frozen_string_literal: true
+
+require 'rspec'
+
+describe Iuliia do
```
Comment (adnikiforov) [inline spec/iuliia/schema_spec.rb]:
```suggestion
describe Iuliia::Schema do
```

File: spec/iuliia/schema_spec.rb [hunk 3]
```diff
@@ -0,0 +1,27 @@
...
+  describe 'Schema loading' do
+    describe '#opening' do
```
Comment (adnikiforov) [inline spec/iuliia/schema_spec.rb]:
```suggestion
  describe '#[]' do
```

**Review by adnikiforov — COMMENTED** [review]
Thank you for the contribution! I've left some comments, please take a look.

File: spec/iuliia/schema_spec.rb (hunk 3 above)
Comment (theendcomplete) [reply spec/iuliia/schema_spec.rb]: applied

File: spec/iuliia/schema_spec.rb (hunk 2 above)
Comment (theendcomplete) [reply spec/iuliia/schema_spec.rb]: applied

File: lib/iuliia/schema.rb (hunk 1 above)
Comment (theendcomplete) [reply lib/iuliia/schema.rb]: now user gets 'Specified schema does not exist' message and the gem raises the exception:

```
irb(main):001:0> Iuliia::Schema['gost_779a']
Traceback (most recent call last):
        5: from bin/console:15:in `<main>'
        4: from (irb):1
        3: from /home/theendcomplete/Documents/projects/OS/iuliia-rb/lib/iuliia/schema.rb:10:in `[]'
        2: from /home/theendcomplete/Documents/projects/OS/iuliia-rb/lib/iuliia/schema.rb:25:in `block in schemas'
        1: from /home/theendcomplete/Documents/projects/OS/iuliia-rb/lib/iuliia/schema.rb:30:in `load_schema'
Iuliia::Exceptions::NonExistentSchemaException (Specified schema does not exist)
irb(main):002:0> 
```

**Review by adnikiforov — APPROVED** [review]
Looks good to me! 🚀
